[package]
name = "printpdf"
version = "0.5.0"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
repository = "https://github.com/fschutt/printpdf"
homepage = "https://github.com/fschutt/printpdf"
license = "MIT"
readme = "README.md"
description = "Rust library for writing PDF files"
keywords = ["pdf", "gui", "graphics", "wkhtmltopdf"]
categories = ["gui"]
exclude = ["./assets/*", "./doc/*", "./examples/*"]
autoexamples = false

[dependencies]
# minimum dependencies
lopdf = { version = "0.27.0", default-features = false, features = ["pom_parser"] }
rusttype = { version = "0.8.2", default-features = false, features = ["std"] }
time = { version = "0.2.11", default-features = false, features = ["std"] }
# optional: logging
log = { version = "0.4.8", optional = true }
# image reading (png)
image = { version = "0.23", optional = true, default-features = false, features = ["png"] }
# svg support (svg -> pdf xobject)
svg2pdf = { version = "0.1.0", optional = true }
pdf-writer = { version = "0.4.1", optional = true }
usvg = { version = "0.19.0", optional = true }

[features]
default = []
# cargo clippy
clippy = []
# do not compress PDF streams, useful for debugging
less-optimization = []
# enables logging
logging = ["log"]
# enables image support with some basic formats
embedded_images = ["image"]
# enables extra image formats
ico = ["image/ico", "embedded_images"]
tga = ["image/tga", "embedded_images"]
hdr = ["image/hdr", "embedded_images"]
jpeg_rayon = ["image/jpeg_rayon", "embedded_images"]
dxt = ["image/dxt", "embedded_images"]
dds = ["image/dds", "embedded_images"]
webp = ["image/webp", "embedded_images"]
# enables svg
svg = ["svg2pdf", "usvg", "pdf-writer"]

[target.'cfg(all(target_arch="wasm32",target_os="unknown"))'.dependencies]
js-sys = "0.3.40"

[badges]
travis-ci = { repository = "fschutt/printpdf" }
appveyor = { repository = "fschutt/printpdf" }

[[example]]
name = "bookmark"
default-features = false
required-features = []

[[example]]
name = "circle"
default-features = false
required-features = []

[[example]]
name = "font"
default-features = false
required-features = []

[[example]]
name = "image"
default-features = false
required-features = ["embedded_images"]

[[example]]
name = "no_icc"
default-features = false
required-features = []

[[example]]
name = "page"
default-features = false
required-features = []

[[example]]
name = "shape"
default-features = false
required-features = []

[[example]]
name = "svg"
default-features = false
required-features = ["svg"]
